config:
  eth_priv_key: "43c61d828a271453a39b38c95axxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  env: "testnet"

coins:
  ETH-USD-PERP:
    side: "LONG"
    size: 0.1
    grids: 5
    take_step: 0.003
    grid_step: 1.5
    first_grid_step: 0.5
    order_step: 1.5
  BTC-USD-PERP:
    side: "LONG"
    size: 0.001
    grids: 5
    take_step: 0.003
    grid_step: 1.5
    first_grid_step: 0.5
    order_step: 1.5
